### ISSUE TITLE
Minecraft crashes after joining and doing smth for a minute or 2

### ISSUE THREAD

**Issue by ZhaleTheDoggo** [Songs-of-War/Songs-of-War-Launcher#106]
**Screenshots**
https://gyazo.com/58569a8012e2fe3f567579e70c322be7

**Log file**
[latest.log](https://github.com/Songs-of-War/Songs-of-War-Launcher/files/6711330/latest.log)

**Desktop**
 - OS: Windows
 - Launcher version: 1.10.12

**Additional context**
This is the second time it happens. You join the game, do smth and then it gives you error that mc crashed and you can't play. I've tried to join again but it keeps me in few seconds - minute and then it crashes again.

**Comment by eDexiam** [comment]
Please try disabling "StarLight" in optional mods and let me know if the issue persists

**Comment by ZhaleTheDoggo** [comment]
so far, it worked, it haven't crashed after that
