### ISSUE TITLE
A runtime error has occurred 

### ISSUE THREAD

**Issue by B0SSSK1D** [Songs-of-War/Songs-of-War-Launcher#115]
When I am just playing normally on the Songs of War server sometimes for the past couple of days my game would go back to the launcher and it would say ''A runtime error has occurred, most likely due to a file edit.''  I don't really have any more details to give about the issue.

**Comment by eDexiam** [comment]
Please try the latest alpha build

**Comment by eDexiam** [comment]
No response from author
