### ISSUE TITLE
Error massage

### ISSUE THREAD

**Issue by liorad** [Songs-of-War/Songs-of-War-Launcher#127]
```
TypeError: Cannot read property 'getServer' of null
    at refreshServerStatus (file:///C:/Users/rache/AppData/Local/Programs/songs-of-war-launcher/resources/app.asar/app/assets/js/scripts/landing.js:284:49)
    at file:///C:/Users/rache/AppData/Local/Programs/songs-of-war-launcher/resources/app.asar/app/assets/js/scripts/landing.js:372:46
```

---

Songs of War Game 1.10.13
Electron 12.0.16
win32 10.0.19042
Locale: he

**Comment by eDexiam** [comment]
Hello, when does this issue occur?

**Comment by liorad** [comment]
this issue occurred to me when I was opening the launcher 2 days ago when the launcher was in maintance and the launcher stayed opened for 2 min and it showed me that massage but it doesnt do it anymore
