### ISSUE TITLE
[BUG] for v2.0.0-alpha2

### ISSUE THREAD

**Issue by AlisterVangelis** [Songs-of-War/Songs-of-War-Launcher#137]
There is no exe to download for windows v2.0.0-alpha2 that I could find there was one that said "Songs-of-War-Game-win-2.0.0-alpha2.exe.blockmap" but that doesn't work since its ".blockmap" and not ".exe" please make it easier to download the alpha's if possible, Thanks please have a nice day.

**Comment by eDexiam** [comment]
No longer relevant as of newer versions
