### ISSUE TITLE
[BUG] for v2.0.0-alpha1 the Songs-of-War-Game-win-2.0.0-alpha1.exe

### ISSUE THREAD

**Issue by AlisterVangelis** [Songs-of-War/Songs-of-War-Launcher#138]
Every time after the installation of "Songs Of War"-(Btw downloaded it more than once) when I click the "Songs of War Game" it says error: Cannot Download Update or something. 

Thanks have a wonderfull day

-Alister

![Screenshot 2021-09-28 174745](https://user-images.githubusercontent.com/91517449/135024949-768e08d8-0516-4c5c-a25c-65386a7ba335.png)

**Comment by eDexiam** [comment]
This was due to a missing artifact on the release but this is no longer relevant as of now
