### ISSUE TITLE
the version 2.0.0-Alpha5

### ISSUE THREAD

**Issue by ZhaleTheDoggo** [Songs-of-War/Songs-of-War-Launcher#170]
ok so, considering that the alpha5 (which has the security update) is the one which supports microsoft log in. Well, apparently when you try to log in, it only shows the exact log in option as the original launcher has. (the one which doesn't support microsoft accounts)
so basically you can't log in if your minecraft account is microsoft account. 
 
would be nice if this version would have the ms account log in option.

-Zhale

**Comment by eDexiam** [comment]
Wrong build was attached to the release, this has been fixed since
