### ISSUE TITLE
[BUG] Buggy multi-account login

### ISSUE THREAD

**Issue by Damascusari** [Songs-of-War/Songs-of-War-Launcher#178]
**Describe the bug**
Login works... mostly, for 2 Microsoft accounts, does not for a third, sign out is buggy. Authenticator app codes don't work for 2fa, only email codes. This is only an issue with this launcher for me, the codes work with everything else I've ever used them for, including the Minecraft Technic Launcher.

Sometimes you can log in to the second account and the launcher still launches with the first account.

This time I found the log files.

**To Reproduce**
Sign in and sign out in various ways.

**Log file**

[2022-02-18-1.log.gz](https://github.com/Songs-of-War/Songs-of-War-Launcher/files/8102996/2022-02-18-1.log.gz)
[2022-02-18-2.log.gz](https://github.com/Songs-of-War/Songs-of-War-Launcher/files/8102997/2022-02-18-2.log.gz)
[2022-02-18-3.log.gz](https://github.com/Songs-of-War/Songs-of-War-Launcher/files/8102998/2022-02-18-3.log.gz)

**Comment by eDexiam** [comment]
Hi, thanks for the report, please note that I need the launcher log which is located in `%appdata%/Songs of War Game/latest.log`, if you can try to reproduce the issues and send that log that'd be great! (Please note that restarting the launcher wipes that files effectively rendering it useless for me).

Also, please attach your launcher version number.
Thanks!

**Comment by eDexiam** [comment]
That's great news, I'll be closing the issue now, if there's any more problems with account or logins feel free to create a new issue.
