### ISSUE TITLE
Intel HD Graphics 3000 Crashes on Win10

### ISSUE THREAD

**Issue by lucasboss45** [Songs-of-War/Songs-of-War-Launcher#23]
```
C:\Users\kotia\AppData\Local\Programs\Songs-of-War-Launcher\resources\app.asar\app\assets\js\loggerutil.js:11 [Minecraft] [13:23:16] [main/INFO]: [org.lwjgl.glfw.GLFWErrorCallback$1:invoke:105]: 	Description : WGL: The driver does not appear to support OpenGL
[13:23:16] [main/INFO]: [org.lwjgl.glfw.GLFWErrorCallback$1:invoke:106]: 	Stacktrace  :
[13:23:16] [main/INFO]: [org.lwjgl.glfw.GLFWErrorCallback$1:invoke:110]: org.lwjgl.glfw.GLFW.nglfwCreateWindow(GLFW.java:1714)
[13:23:16] [main/INFO]: [org.lwjgl.glfw.GLFWErrorCallback$1:invoke:110]: org.lwjgl.glfw.GLFW.glfwCreateWindow(GLFW.java:1897)
```

Possible fix:
https://gist.github.com/rb-dahlb/26f316c5b6089807a139fc44ee69f0d1

Related
https://discourse.paraview.org/t/opengl-not-supported-in-windows-10-and-intel-hd-graphics-card-glew-could-not-be-intialized-missing-gl-version/2701

**Comment by lucasboss45** [comment]
Install command:
`sdbinst.exe -p -q <path to the file>`

**Comment by lucasboss45** [comment]
Potential fixes
https://github.com/pal1000/save-legacy-intel-graphics

**Comment by lucasboss45** [comment]
No more instances of the issue have been reporting, leaving the issue open just in case.

**Comment by forkpoweroutlet** [comment]
As much as I want to make the server widely accessible, Windows 10 doesn't even support Intel HD Graphics 3000, so I don't really think it's entirely our responsibility. Should I close this?

**Comment by lucasboss45** [comment]
Leave open in case we get more reports of it.

**Comment by lucasboss45** [comment]
Will re-open if necessary
