### ISSUE TITLE
[BUG] Play button status gets overriden on server change

### ISSUE THREAD

**Issue by lucasboss45** [Songs-of-War/Songs-Of-War-Launcher#29]

**Comment by forkpoweroutlet** [comment]
Could this be addressed by simply disabling the server changer while the user is in game?
I feel like that would be among the easiest ways to go about it.

**Comment by lucasboss45** [comment]
Seems good

**Comment by forkpoweroutlet** [comment]
Alright, check my latest commit to dev. I haven't tested it extensively yet, though.

**Comment by forkpoweroutlet** [comment]
My commit didn't make it into production, so I'll add it in next update.
