### ISSUE TITLE
Try forcing the update of the launcher in the background if it's closed and update is ready

### ISSUE THREAD

**Issue by lucasboss45** [Songs-of-War/Songs-of-War-Launcher#31]
Note: will probably have to change the installer script 

- [ ] Run the update installer on launcher closure
- [ ] Refactor installer script to automatically update launcher (So that there is no need for user input when updating)
- [ ] _Automatic update download in the background (Possibly limit the download bandwith to prevent slowdowns on the OS)_

**Comment by forkpoweroutlet** [comment]
Does the launcher already have a background task running? I'm not sure whether to set one up for updates and updates alone.

**Comment by lucasboss45** [comment]
A background task would be looked into later for the updater, for now we just need a way for the launcher to update itself when closed.

**Comment by forkpoweroutlet** [comment]
Ah, okay. So it'll update and then close.

**Comment by lucasboss45** [comment]
So we have 2 ways to go about this.

Either we update it in the background after it gets closed
Or
We update on launcher startup (Would be safer in terms of not corrupting the installation)

**Comment by lucasboss45** [comment]
No longer relevant
