### ISSUE TITLE
[BUG] Random connection timeouts

### ISSUE THREAD

**Issue by lucasboss45** [Songs-of-War/Songs-of-War-Launcher#56]
Unsure why the launcher seems to timeout the connection sometimes
https://ghostbin.co/paste/xfbc3

Potential fixes:
- An actual retry system

**Comment by forkpoweroutlet** [comment]
Was this fixed in a recent update? You mentioned a retry implementation on Discord.

**Comment by lucasboss45** [comment]
> Was this fixed in a recent update? You mentioned a retry implementation on Discord.

Yes it was fixed, I will now close
