### ISSUE TITLE
[ Feature Request ]  ViveCraft Support (Allows players to play in VR)

### ISSUE THREAD

**Issue by ghost** [Songs-of-War/Songs-of-War-Launcher#78]
**Describe the solution you'd like**
I would like it to be possible for me or someone else to be able to use the vivecraft installer on the SOWLauncher to Boot the server in VR Or to have a separate profile that lets a person run the server in VR from the launcher

=
**Additional context**
I just think VR will be worth doing on the server and I know its possible (I tested it in singleplayer)

**Comment by SUPERN00Bthefirst** [comment]
This feature would mean the disabling of Xero's Minimap as it prevents game launch.

**Comment by eDexiam** [comment]
There have been changes to the mods, making me doubtful vivecraft will work anymore, if you still want to push out this feature, feel free to test out if Vivecraft is still compatible with the latest mods since I don't have a VR setup

**Comment by eDexiam** [comment]
No longer possible as we're moving to Fabric as the modloader in the very near future.
