### ISSUE TITLE
Launcher won't open, error log pops up

### ISSUE THREAD

**Issue by Adventureman404** [Songs-of-War/Songs-of-War-Launcher#89]
```
TypeError: result.toFixed is not a function
    at Object.dataValue (C:\Users\NAME\AppData\Local\Programs\songs-of-war-launcher\resources\app.asar\node_modules\wmic-sys-info\lib\helpers.js:31:17)
    at C:\Users\NAME\AppData\Local\Programs\songs-of-war-launcher\resources\app.asar\node_modules\wmic-sys-info\index.js:75:29
    at ChildProcess.exithandler (child_process.js:303:7)
    at ChildProcess.emit (events.js:315:20)
    at maybeClose (internal/child_process.js:1021:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:286:5)
```

---

Songs of War Game 1.10.7
Electron 11.4.2
win32 6.1.7601
Locale: en-US

**Comment by forkpoweroutlet** [comment]
Can you elaborate on where you were in the launcher when the error occurred?

**Comment by Adventureman404** [comment]
> Can you elaborate on where you were in the launcher when the error occurred?

I was trying to start up the launcher itself, it was newly installed and this error occurred. I uninstalled it then reinstalled it again, but the error continued to happen.

**Comment by Adventureman404** [comment]
Also just to add, when i try to run the setup launcher, the launcher would be stuck on the loading screen itself and nothing would happen afterwards.

**Comment by eDexiam** [comment]
Could you enter this command in a terminal and write the result?
`wmic CPU get Name,NumberOfCores,NumberOfLogicalProcessors`

**Comment by Kyberoff** [comment]
> Could you enter this command in a terminal and write the result?
> `wmic CPU get Name,NumberOfCores,NumberOfLogicalProcessors`

Name                                      NumberOfCores  NumberOfLogicalProcessors
Intel(R) Core(TM) i7-8700K CPU @ 3.70GHz  6              12

That's what it shows for me.

**Comment by Adventureman404** [comment]
> Could you enter this command in a terminal and write the result?
> `wmic CPU get Name,NumberOfCores,NumberOfLogicalProcessors`

Name                                     NumberOfCores  NumberOfLogicalProcessor
s
Intel(R) Core(TM) i5-4570 CPU @ 3.20GHz  4              4

This is what I got for mine

**Comment by eDexiam** [comment]
Try this version https://ufile.io/zez9e69l

**Comment by eDexiam** [comment]
Turns out the other link was bad, try this: https://mega.nz/file/wlQliK6L#NETqmijH9uVBjN3zgdl9HN90l8leDNGGn9Iy5I_ZzsE
