### ISSUE TITLE
boooooonk

### ISSUE THREAD

**Issue by VectoridEverlast** [Songs-of-War/Songs-of-War-Launcher#93]
```
TypeError: result.toFixed is not a function
    at Object.dataValue (C:\Users\Vectorid\AppData\Local\Programs\songs-of-war-launcher\resources\app.asar\node_modules\wmic-sys-info\lib\helpers.js:31:17)
    at C:\Users\Vectorid\AppData\Local\Programs\songs-of-war-launcher\resources\app.asar\node_modules\wmic-sys-info\index.js:75:29
    at ChildProcess.exithandler (child_process.js:303:7)
    at ChildProcess.emit (events.js:315:20)
    at maybeClose (internal/child_process.js:1021:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:286:5)
```

---

Songs of War Game 1.10.7
Electron 11.4.2
win32 10.0.19042
Locale: en-US

**Comment by eDexiam** [comment]
Hi, could you enter the command `wmic CPU get Name,NumberOfCores,NumberOfLogicalProcessors` into a command prompt and tell me the result?

**Comment by eDexiam** [comment]
Duplicate #89

**Comment by VectoridEverlast** [comment]
Hello, I am very sorry for not responding for a while... how exactly do I pull up the command prompt?  When I open up the application, it just reports the error & just continues to load forever  From: eDexiamSent: Tuesday, 18 May 2021 2:47 PMTo: Songs-of-War/Songs-of-War-LauncherCc: Vectorid Everlast; AuthorSubject: Re: [Songs-of-War/Songs-of-War-Launcher] boooooonk (#93) Duplicate #89—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.
