### ISSUE TITLE
Unable to connect with the servers to check if an updates are available. 

### ISSUE THREAD

**Issue by ArvolyXSL** [Songs-of-War/Songs-of-War-Launcher#98]
```
TypeError: Cannot read property 'getServer' of null
    at refreshServerStatus (file:///C:/Users/user-pc/AppData/Local/Programs/songs-of-war-launcher/resources/app.asar/app/assets/js/scripts/landing.js:284:49)
    at file:///C:/Users/user-pc/AppData/Local/Programs/songs-of-war-launcher/resources/app.asar/app/assets/js/scripts/landing.js:372:46
```

---

Songs of War Game 1.10.12
Electron 12.0.7
win32 10.0.19042
Locale: en-US

**Comment by eDexiam** [comment]
Can you access [this](https://mysql.songs-of-war.com/distribution.json) in a normal web browser?

**Comment by ArvolyXSL** [comment]
All it does is bring up the code used to tell the client from where the launcher needs to download the mods from. Not much else is told or explicitly informs me on what I must do, I can just download the files, but there is no guarantee it will work. I will try it none the less. I will inform you of the outcome.

**Comment by eDexiam** [comment]
Try running the latest pre-release version in the releases

**Comment by ArvolyXSL** [comment]
It seems to be working now, thank you.From: eDexiamSent: Friday, 11 June 2021 15:26To: Songs-of-War/Songs-of-War-LauncherCc: ArvolyXSL; AuthorSubject: Re: [Songs-of-War/Songs-of-War-Launcher] Unable to connect with the servers to check if an updates are available. (#98) Try running the latest pre-release version in the releases

**Comment by eDexiam** [comment]
I'll close this then, if you get any other problems feel free to re-open it
